target "V1_New" do
project 'V1_New.project'
platform :ios, "9.0"
pod 'Masonry'
pod 'MJExtension'
pod 'YYKit'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'LBXScan'                   #二维码扫描库
#pod 'JXCategoryView'
end
